# This is a basic workflow to help you get started with Actions

name: Screenshot and Vulnerability

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Screenshot Website
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://cianosullivan.me/
        destination: screenshot.png
        full-page: true
    - name: Test for public javascript library vulnerabilities 
      uses: lirantal/is-website-vulnerable@master
      with:
        scan-url: "https://cianosullivan.me"
